steps:
- task: PowerShell@2
  displayName: 'Test'
  inputs:
    targetType: inline
    pwsh: ${{ parameters.pwsh }}
    script: |
      Import-Module .\tools\appveyor.psm1
      Invoke-AppveyorTest -CheckoutPath $env:BUILD_SOURCESDIRECTORY
- task: PublishTestResults@2
  inputs:
    testRunner: NUnit
    testResultsFiles: 'TestResults.xml'
    condition: succeededOrFailed()